name: ImandraX VSCode Extension CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4

      - name: 'Install vsce'
        run: npm install -g @vscode/vsce

      - name: 'Install esbuild'
        run: npm install esbuild

      - name: 'Build extension'
        run: npm install; vsce package

      - uses: actions/upload-artifact@v4
        with:
          path: imandrax-*.vsix

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    # if: github.ref == 'refs/heads/main'
    steps:
    - run: pwd
    - run: ls -lah
    - run: ls -lah ..
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "imandrax-*.vsix"
        name: "ImandraX"
        body: "The latest release of the ImandraX VSCode extension"
        tag: latest
        allowUpdates: true